spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaleZone: http://localhost:8761/eureka/


server:
  port: 8768
zuul:
  routes:
#    myproduct:
#      path: /myproduct/**
#      serviceId: product
    product: /myproduct/**
#management:
#  security:
#    enabled: false